e01のシーンを整理
2022-4J-group-O/Prologue pull request #17
Opened 2022-11-07 16:32 UTC by tt6-mzn

## e01のシーンをよりそれっぽく変更してみました
動作確認をよろしくお願いします
もっときれいに書けるような気もするけどとりあえず実現方法の候補として

## 変更点
* e02のシーンの仕組みをだいぶ変えました
* いくつかのファイルを移動したり、renameしたりしました

2022-11-08 13:17 UTC, Esu0 requested changes
> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
>   File "game/scripts/02_e_最初の部屋脱出.rpy", line 27, in script
>     if store.draggable == "Key":
>   File "game/scripts/02_e_最初の部屋脱出.rpy", line 27, in <module>
>     if store.draggable == "Key":
> AttributeError: 'StoreModule' object has no attribute 'draggable'
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "game/scripts/02_e_最初の部屋脱出.rpy", line 27, in script
>     if store.draggable == "Key":
>   File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
>     if renpy.python.py_eval(condition):
>   File "C:\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
>     return py_eval_bytecode(code, globals, locals)
>   File "C:\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
>     return eval(bytecode, globals, locals)
>   File "game/scripts/02_e_最初の部屋脱出.rpy", line 27, in <module>
>     if store.draggable == "Key":
> AttributeError: 'StoreModule' object has no attribute 'draggable'
> 
> Windows-10-10.0.19045 AMD64
> Ren'Py 8.0.3.22090809
> Prologue 1.0
> Tue Nov  8 22:15:13 2022

Ctrlキーを押すと例外が発生した。
pause中は読み進められないけどスキップは有効みたいだから無効にしといて

2022-11-08 13:19 UTC, Esu0 commented
↑e02に入った辺りのこと

2022-11-09 09:23 UTC, tt6-mzn commented
スキップに関して修正したものをpushしました

2022-11-09 10:11 UTC, Esu0 approved these changes
LGTM

2022-11-09 10:11 UTC, merged