プロログの画像の変更とプログラムの追加
2022-4J-group-O/Prologue pull request #30
Opened 2022-12-08 12:07 UTC by frisadl

Itemの位置とプログラムの確認お願いします。

2022-12-08 12:08 UTC, frisadl commented
本をクリックしてから、鍵のファイルを生成するけど、鍵の表示がちょっと遅い。どうすればいい？

2022-12-11 09:34 UTC, Esu0 commented
鍵を表示したいタイミングでスクリーンをもう一回呼び出せばできるよ

2022-12-11 11:23 UTC, Esu0 commented
これで大丈夫

2022-12-11 11:28 UTC, Esu0 requested changes
`door_show`変数の名前を`pr_door_show`に変更してほしい
ほかの部屋で使う変数名と重複する可能性があるので

2022-12-13 12:37 UTC, Esu0 approved these changes
これで多分大丈夫

2022-12-13 12:38 UTC, merged