reset_roomのエラー処理・Mainを実行したことの検出
2022-4J-group-O/Prologue pull request #42
Opened 2022-12-19 12:57 UTC by Esu0

# 実装した内容

* reset_roomでPermissionErrorを送出した場合に戻り値を返すようにした
* Mainプログラムを実行したかを判定する関数を追加

## 追加した関数

* `check_main()` Mainプログラムをすでに実行していたら`True`、そうでなければ`False`を返す

## 追加したクラス

* なし

## 追加した変数・フラグ

* `define main_built_flg_path = "game/data/main_nbuilt"`Mainを起動していないときに存在するファイルのパス

## その他の変更

* パスが`game/data/main_nbuilt`であるファイルを追加

## デバッグしてほしいところ

* `reset_room()`が例外を送出しないか

2022-12-20 13:27 UTC, tt6-mzn requested changes

2022-12-20 13:27 UTC, tt6-mzn commented on game/zz_late_eval/functions/function01.rpy
> +        return not os.path.isfile(os.path.join(user_dir_path, main_built_flg_path))
`user_dir_path`だと、`game_data`以下のフォルダを検索しちゃうからまずいと思う
![image](https://user-images.githubusercontent.com/60829248/208677759-859f2423-15ac-4050-b267-08c4db62985f.png)

2022-12-21 12:37 UTC, Esu0 commented
修正した

2022-12-22 04:40 UTC, tt6-mzn approved these changes
LGTM

2022-12-22 04:47 UTC, merged